# Generated by Django 3.1.4 on 2020-12-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AddField(
            model_name='photo',
            name='filename',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='url',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
