# Generated by Django 3.1.4 on 2020-12-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201210_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='rubrics',
            field=models.ManyToManyField(blank=True, related_name='news', to='api.Rubric'),
        ),
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='news', to='api.Tag'),
        ),
    ]
