version: "3"

services:
  news-serve:
    container_name: news-serve
    build:
      context: ./
      dockerfile: ./docker/backend.Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    expose:
      - 8000
    depends_on:
      - news-postgres
    env_file:
      - .env
    volumes:
      - ./news_app:/code
    networks: 
      - news_net

  news-front:
    container_name: news-front
    build:
      context: ./
      dockerfile: ./docker/frontend.Dockerfile
    command: npm start
    env_file:
      - .env
    expose:
      - 3000
    volumes:
      - ./frontend:/code
    networks: 
      - news_net
      
  nginx:
    build:
      context: ./
      dockerfile: ./docker/nginx.Dockerfile
    ports:
      - 7000:7000
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    networks: 
      - news_net
    depends_on:
      - news-serve
      - news-front


  news-postgres:
    container_name: news-postgres
    image: postgres:13
    restart: on-failure
    expose:
      - 5432
    env_file:
      - .env
    volumes:
      - news_app-postgres:/var/lib/postgresql/data
    networks: 
      - news_net

volumes:
  news_app-postgres:

networks: 
    news_net:
        driver: bridge
